// Generated by CoffeeScript 1.3.3

/*
Welcome to Coffeescript. Below is a (small) example of what some coffeescript
code may look like. Use the 'coffee -p [filename]' command in terminal to see how it
will look once it is compiled into javascript. One of the nice things about coffeescript
is that the compiled code is still readable!
*/


(function() {
  var Intro;

  Intro = (function() {

    function Intro(name) {
      this.name = name;
      this.counter = 0;
    }

    Intro.prototype.incrementCounter = function() {
      return this.counter++;
    };

    Intro.prototype.nameAsArray = function() {
      var i, result, _i, _len, _ref, _results;
      _ref = this.name;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        _results.push(result = i);
      }
      return _results;
    };

    Intro.prototype.attachClickListener = function() {
      var _this = this;
      return $('#button').click(function() {
        return _this.incrementCounter();
      });
    };

    Intro.prototype.isCounterEqualTo2 = function() {
      return this.counter === 2;
    };

    return Intro;

  })();

}).call(this);
