// Generated by CoffeeScript 1.3.3
(function() {
  var another, obj;

  obj = {
    key: 'value',
    '1test': 123
  };

  another = {
    key: 'value',
    "function": function() {
      return console.log('a function');
    },
    nested: {
      example: ['an', 'array']
    }
  };

  another["function"]();

}).call(this);
