// Generated by CoffeeScript 1.3.3
(function() {
  var Animal, Cat, Dog, MyClass, doug, mrSnuffles, myClass,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MyClass = (function() {

    function MyClass() {
      console.log('I am ALIVE');
    }

    MyClass.prototype.announce = function() {
      return console.log('I am a MyClass');
    };

    return MyClass;

  })();

  myClass = new MyClass();

  Animal = (function() {

    function Animal(name) {
      this.name = name;
    }

    Animal.prototype.move = function(meters) {
      return console.log('moved ' + meters + ' meters');
    };

    return Animal;

  })();

  Dog = (function(_super) {

    __extends(Dog, _super);

    function Dog() {
      return Dog.__super__.constructor.apply(this, arguments);
    }

    Dog.prototype.move = function() {
      console.log('I AM A DOG! YOU ARE MY BEST FRIEND!');
      return Dog.__super__.move.call(this, 10);
    };

    return Dog;

  })(Animal);

  Cat = (function(_super) {

    __extends(Cat, _super);

    function Cat() {
      return Cat.__super__.constructor.apply(this, arguments);
    }

    Cat.prototype.move = function() {
      console.log('Go away human, you are beneath me.');
      return Cat.__super__.move.call(this, 1);
    };

    return Cat;

  })(Animal);

  doug = new Dog('doug');

  mrSnuffles = new Cat('Mr Snuffles');

  doug.move();

  mrSnuffles.move();

}).call(this);
